osx_image: xcode9
language: objective-c
script:
  - |
    xcodebuild test \
     -project Snippet.xcodeproj \
     -scheme Snippet \
     -sdk iphonesimulator \
     -destination 'platform=iOS Simulator,name=iPhone X,OS=latest' \
    | xcpretty